version: "3"

services:
  auth:
    container_name: auth
    image: pomerium/pomerium:latest
    volumes:
      - ./pomerium/config.yaml:/pomerium/config.yaml:ro
      - ./pomerium/data/certs:/data/certs:rw
      - ./pomerium/data/jwks:/data/jwks:ro
    ports:
      - 443:443
    env_file:
      - pomerium.env
  verify:
    image: pomerium/verify:latest
    expose:
      - 8000